"""initial_schema

Revision ID: d53bd0e2d398
Revises: 
Create Date: 2026-04-22 19:50:38.584813

"""
import os
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from dotenv import load_dotenv
from passlib.context import CryptContext


# revision identifiers, used by Alembic.
revision: str = 'd53bd0e2d398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def _load_seed_settings() -> tuple[str, str, str]:
    project_root = Path(__file__).resolve().parents[2]
    load_dotenv(project_root / ".env")
    return (
        os.getenv("DEFAULT_ADMIN_USERNAME", "admin"),
        os.getenv("DEFAULT_ADMIN_EMAIL", "admin@local.dev"),
        os.getenv("DEFAULT_ADMIN_PASSWORD", "admin1234"),
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tenant_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_tenant_domains_id'), 'tenant_domains', ['id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    op.create_index(op.f('ix_user_tenants_id'), 'user_tenants', ['id'], unique=False)
    admin_username, admin_email, admin_password = _load_seed_settings()
    users_table = sa.table(
        'users',
        sa.column('username', sa.String(length=80)),
        sa.column('email', sa.String(length=150)),
        sa.column('password_hash', sa.String(length=255)),
        sa.column('is_active', sa.Boolean()),
        sa.column('is_superadmin', sa.Boolean()),
    )
    op.bulk_insert(
        users_table,
        [
            {
                'username': admin_username,
                'email': admin_email,
                'password_hash': pwd_context.hash(admin_password),
                'is_active': True,
                'is_superadmin': True,
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tenants_id'), table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index(op.f('ix_tenant_domains_id'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
